# Generated by Django 5.0.6 on 2024-06-18 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='nombres')),
                ('first_name', models.CharField(max_length=128, verbose_name='primer apellido')),
                ('last_name', models.CharField(max_length=128, null=True, verbose_name='segundo apellido')),
                ('picture', models.ImageField(upload_to='contacts/')),
                ('birthday', models.DateField(null=True)),
                ('email', models.CharField(max_length=128, null=True, verbose_name='correo electronico')),
                ('facebook', models.CharField(max_length=128, verbose_name='facebook')),
                ('x', models.CharField(max_length=128, verbose_name='antiguo twitter')),
                ('linkedin', models.CharField(max_length=128, verbose_name='linkedin')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='ContactPhoneNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=20, verbose_name='telefono')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
            ],
            options={
                'db_table': 'contact_phone_numbers',
            },
        ),
    ]
