# Generated by Django 5.0.6 on 2024-06-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='facebook',
            field=models.CharField(max_length=128, null=True, verbose_name='facebook'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='linkedin',
            field=models.CharField(max_length=128, null=True, verbose_name='linkedin'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='x',
            field=models.CharField(max_length=128, null=True, verbose_name='antiguo twitter'),
        ),
    ]
