# Generated by Django 5.0.6 on 2024-06-25 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contact_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactphonenumbers',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='phone', to='contacts.contact'),
        ),
    ]
