# Generated by Django 5.0.6 on 2024-06-18 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='titulo')),
                ('description', models.CharField(max_length=512, null=True, verbose_name='descripcion')),
                ('reminder_date', models.DateField(verbose_name='fecha_recordatorio')),
                ('reminder_hour', models.TimeField(verbose_name='hora_recordatorio')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reminders',
            },
        ),
    ]
